/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-13 01:45:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class navigation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.1.2.RELEASE.jar", Long.valueOf(1600669116782L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1600669116651L));
    _jspx_dependants.put("jar:file:/C:/Users/HUSTAR_19/Desktop/SpringDemo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hustar-pms/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/HUSTAR_19/Desktop/SpringDemo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hustar-pms/WEB-INF/lib/spring-webmvc-4.1.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1415631592000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <nav class=\"navbar navbar-default navbar-static-top\" role=\"navigation\" style=\"margin-bottom: 0\">\n");
      out.write("            <div class=\"navbar-header\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"index\">");
      if (_jspx_meth_s_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</a>\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                    <span class=\"icon-bar\"></span>\n");
      out.write("                </button>\n");
      out.write("\n");
      out.write("\t            <ul class=\"nav navbar-top-links navbar-right\">\n");
      out.write("\t                <!-- /.dropdown -->\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t                <!-- /.dropdown -->\n");
      out.write("\t                <li class=\"dropdown\">\n");
      out.write("\t                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">\n");
      out.write("\t                        <i class=\"fa fa-user fa-fw\"></i>  <i class=\"fa fa-caret-down\"></i>\n");
      out.write("\t                    </a>\n");
      out.write("\t                    <ul class=\"dropdown-menu dropdown-user\">\n");
      out.write("\t                        <li><a href=\"memberForm\"><i class=\"fa fa-user fa-fw\"></i> ");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("</a></li>\n");
      out.write("\t                        <li><a href=\"searchMember\"><i class=\"fa fa-users fa-fw\"></i> ");
      if (_jspx_meth_s_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</a></li>\n");
      out.write("\t                        <li class=\"divider\"></li>\n");
      out.write("\t                        <li><a href=\"memberLogout\"><i class=\"fa fa-sign-out fa-fw\"></i> Logout</a>\n");
      out.write("\t                        </li>\n");
      out.write("\t                    </ul>\n");
      out.write("\t                    <!-- /.dropdown-user -->\n");
      out.write("\t                </li>\n");
      out.write("\t                <!-- /.dropdown -->\n");
      out.write("\t            </ul>\n");
      out.write("\t            <!-- /.navbar-top-links -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-header -->\n");
      out.write("\n");
      out.write("            <div class=\"navbar-default sidebar\" role=\"navigation\">\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\n");
      out.write("                    <ul class=\"nav\" id=\"side-menu\">\n");
      out.write("                        <li class=\"sidebar-search\">\n");
      out.write("                           \t<form id=\"searchForm\" name=\"searchForm\"  method=\"post\" action=\"boardList\">\n");
      out.write("                                <input type=\"hidden\" name=\"searchType\" value=\"brdtitle,brdmemo\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"input-group custom-search-form\">\n");
      out.write("\t                                <input class=\"form-control\" type=\"text\" name=\"globalKeyword\" id=\"globalKeyword\" placeholder=\"Search...\">\n");
      out.write("\t                                <span class=\"input-group-btn\">\n");
      out.write("\t                                    <button class=\"btn btn-default\" type=\"button\" onclick=\"fn_search()\">\n");
      out.write("\t                                        <i class=\"fa fa-search\"></i>\n");
      out.write("\t                                    </button>\n");
      out.write("\t                                </span>\n");
      out.write("\t                            </div>                           \t\n");
      out.write("                            </form>\n");
      out.write("\t                                <script>\n");
      out.write("\t                                \tfunction fn_search(){\n");
      out.write("\t                                \t\tif ($(\"#globalKeyword\").val()!==\"\") {\n");
      out.write("\t\t                                \t\t$(\"#searchForm\").submit();\n");
      out.write("\t                                \t\t}\n");
      out.write("\t                                \t}\n");
      out.write("\t                                </script>                            <!-- /input-group -->\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"boardList\"><i class=\"fa fa-files-o fa-fw\"></i> ");
      if (_jspx_meth_s_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#\"><i class=\"fa fa-music fa-fw\"></i> 샘플<span class=\"fa arrow\"></span></a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"nav nav-second-level\">\n");
      out.write("                                <li>\n");
      out.write("                                    <a href=\"sample1\">샘플 1: 조직도/사용자</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("\t\t                            <a href=\"sample2\">샘플 2: 날짜 선택 </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("\t\t                            <a href=\"sample3\">샘플 3: 챠트</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("\t\t                            <a href=\"sample4\">샘플 4: List & Excel</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("\t\t                            <a href=\"crudList\">샘플 5: CRUD</a>\n");
      out.write("                                </li>\n");
      out.write("                                <li>\n");
      out.write("\t\t                            <a href=\"chkList\">샘플 6: Multy Checkbox</a>\n");
      out.write("                                </li>\n");
      out.write("\t                        </ul>                            \n");
      out.write("                        </li>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\t        \n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("                <!-- /.sidebar-collapse -->\n");
      out.write("            </div>\n");
      out.write("            <!-- /.navbar-static-side -->\n");
      out.write("        </nav>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_s_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f0_reused = false;
    try {
      _jspx_th_s_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f0.setParent(null);
      // /WEB-INF/jsp/common/navigation.jsp(7,53) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f0.setCode("common.projectTitle");
      int[] _jspx_push_body_count_s_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f0 = _jspx_th_s_005fmessage_005f0.doStartTag();
        if (_jspx_th_s_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f0);
      _jspx_th_s_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/common/navigation.jsp(17,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alertcount>0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t                <li class=\"dropdown\">\n");
          out.write("\t\t                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" onclick=\"showAlertList()\">\n");
          out.write("\t\t                        <i class=\"fa fa-bell fa-fw\"></i>  <i class=\"fa fa-caret-down\"></i>\n");
          out.write("\t\t                        \t<div class=\"msgAlert\">");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("</div>\n");
          out.write("\t\t                    </a>\n");
          out.write("\t\t                    <script>\n");
          out.write("\t\t                    \tfunction showAlertList(){\n");
          out.write("\t\t                    \t\t$.ajax({\n");
          out.write("\t\t                    \t\t\turl: \"alertList4Ajax\", \n");
          out.write("\t\t                    \t\t\tdataType: \"html\",\n");
          out.write("\t\t                    \t\t\ttype:\"post\", \n");
          out.write("\t\t                    \t\t\tsuccess: function(result){\n");
          out.write("\t\t                    \t\t\t\tif (result!==\"\") {\n");
          out.write("\t\t                    \t\t\t\t\t$(\"#alertlist\").html(result);\n");
          out.write("\t\t                    \t\t\t\t}\n");
          out.write("\t\t                    \t\t\t}\n");
          out.write("\t\t                    \t\t})\t\t                    \t\t\n");
          out.write("\t\t                    \t}\n");
          out.write("\t\t                    </script>\n");
          out.write("\t\t                    <ul id=\"alertlist\" class=\"dropdown-menu dropdown-alerts\">\n");
          out.write("\t\t                    </ul>\n");
          out.write("\t\t                    <!-- /.dropdown-alerts -->\n");
          out.write("\t\t                </li>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/jsp/common/navigation.jsp(21,49) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${alertcount}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/jsp/common/navigation.jsp(48,83) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.usernm}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f1_reused = false;
    try {
      _jspx_th_s_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f1.setParent(null);
      // /WEB-INF/jsp/common/navigation.jsp(49,86) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f1.setCode("memu.users");
      int[] _jspx_push_body_count_s_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f1 = _jspx_th_s_005fmessage_005f1.doStartTag();
        if (_jspx_th_s_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f1);
      _jspx_th_s_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f2_reused = false;
    try {
      _jspx_th_s_005fmessage_005f2.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f2.setParent(null);
      // /WEB-INF/jsp/common/navigation.jsp(86,84) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f2.setCode("board.boardName");
      int[] _jspx_push_body_count_s_005fmessage_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f2 = _jspx_th_s_005fmessage_005f2.doStartTag();
        if (_jspx_th_s_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f2);
      _jspx_th_s_005fmessage_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f2, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/common/navigation.jsp(111,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userrole == \"A\"}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t                        <li>\n");
          out.write("\t                            <a href=\"#\"> ");
          if (_jspx_meth_s_005fmessage_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</a>\n");
          out.write("\t                        </li>\n");
          out.write("\t                        <li>\n");
          out.write("\t                            <a href=\"adBoardGroupList\"><i class=\"fa fa-files-o fa-fw\"></i> ");
          if (_jspx_meth_s_005fmessage_005f4(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</a>\n");
          out.write("\t                        </li>\n");
          out.write("\t                        <li>\n");
          out.write("\t                            <a href=\"#\"><i class=\"fa fa-sitemap fa-fw\"></i> ");
          if (_jspx_meth_s_005fmessage_005f5(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("<span class=\"fa arrow\"></span></a>\n");
          out.write("\t                            <ul class=\"nav nav-second-level\">\n");
          out.write("\t                                <li>\n");
          out.write("\t                                    <a href=\"adDepartment\">");
          if (_jspx_meth_s_005fmessage_005f6(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</a>\n");
          out.write("\t                                </li>\n");
          out.write("\t                                <li>\n");
          out.write("\t                                    <a href=\"adUser\">");
          if (_jspx_meth_s_005fmessage_005f7(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</a>\n");
          out.write("\t                                </li>\n");
          out.write("\t                            </ul>\n");
          out.write("\t                        </li>\n");
          out.write("                             <li>\n");
          out.write("                                 <a href=\"adCodeList\"><i class=\"fa fa-gear fa-fw\"></i> ");
          if (_jspx_meth_s_005fmessage_005f8(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("</a>\n");
          out.write("                             </li>\n");
          out.write("\t                \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f3_reused = false;
    try {
      _jspx_th_s_005fmessage_005f3.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/navigation.jsp(113,42) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f3.setCode("memu.admin");
      int[] _jspx_push_body_count_s_005fmessage_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f3 = _jspx_th_s_005fmessage_005f3.doStartTag();
        if (_jspx_th_s_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f3);
      _jspx_th_s_005fmessage_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f3, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f4_reused = false;
    try {
      _jspx_th_s_005fmessage_005f4.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/navigation.jsp(116,92) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f4.setCode("memu.board");
      int[] _jspx_push_body_count_s_005fmessage_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f4 = _jspx_th_s_005fmessage_005f4.doStartTag();
        if (_jspx_th_s_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f4);
      _jspx_th_s_005fmessage_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f4, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f5 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f5_reused = false;
    try {
      _jspx_th_s_005fmessage_005f5.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/navigation.jsp(119,77) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f5.setCode("memu.organ");
      int[] _jspx_push_body_count_s_005fmessage_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f5 = _jspx_th_s_005fmessage_005f5.doStartTag();
        if (_jspx_th_s_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f5);
      _jspx_th_s_005fmessage_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f5, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f6 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f6_reused = false;
    try {
      _jspx_th_s_005fmessage_005f6.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/navigation.jsp(122,60) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f6.setCode("memu.dept");
      int[] _jspx_push_body_count_s_005fmessage_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f6 = _jspx_th_s_005fmessage_005f6.doStartTag();
        if (_jspx_th_s_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f6);
      _jspx_th_s_005fmessage_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f6, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f7 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f7_reused = false;
    try {
      _jspx_th_s_005fmessage_005f7.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/navigation.jsp(125,54) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f7.setCode("memu.user");
      int[] _jspx_push_body_count_s_005fmessage_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f7 = _jspx_th_s_005fmessage_005f7.doStartTag();
        if (_jspx_th_s_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f7);
      _jspx_th_s_005fmessage_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f7, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_s_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  s:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_s_005fmessage_005f8 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_s_005fmessage_005f8_reused = false;
    try {
      _jspx_th_s_005fmessage_005f8.setPageContext(_jspx_page_context);
      _jspx_th_s_005fmessage_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/jsp/common/navigation.jsp(130,87) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_s_005fmessage_005f8.setCode("memu.code");
      int[] _jspx_push_body_count_s_005fmessage_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_s_005fmessage_005f8 = _jspx_th_s_005fmessage_005f8.doStartTag();
        if (_jspx_th_s_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_s_005fmessage_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_s_005fmessage_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_s_005fmessage_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fs_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_s_005fmessage_005f8);
      _jspx_th_s_005fmessage_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_s_005fmessage_005f8, _jsp_getInstanceManager(), _jspx_th_s_005fmessage_005f8_reused);
    }
    return false;
  }
}
